"""
data/context_writer.py — Claude Projects Context Generator
────────────────────────────────────────────────────────────
Writes a live context file (LIVE_CONTEXT.md) to the repo that your
Claude Project reads automatically.

This is what powers the deep analysis experience in the Claude app.
Every time you open your Claude Project, it has the latest data
injected as context — so you can ask deep, analytical questions like:

  "Look at my last 30 days — what's my biggest weakness?"
  "My win rate dropped this week. What changed?"
  "Given my performance data, should I change any config settings?"
  "Which pairs should I stop trading?"

How the Claude Project integration works:
  1. This script runs every 15 minutes (alongside the market scan)
  2. It writes LIVE_CONTEXT.md with fresh data
  3. You commit this file to GitHub (it's not secret — no API keys)
  4. In Claude.ai, you create a Project and add the GitHub raw URL
     as a document source, OR paste the contents manually
  5. Every Claude conversation in that Project has your live data

The file contains:
  - Current account status and open positions
  - Today's and this week's trade history with full reasoning
  - All-time performance statistics
  - Bot configuration
  - Recent health status
  - A snapshot timestamp so you know how fresh the data is
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from loguru import logger

from bot import config
from data.storage import TradeStorage

CONTEXT_FILE = Path("/app/data/LIVE_CONTEXT.md")


class ContextWriter:
    """Generates and writes the LIVE_CONTEXT.md file."""

    def __init__(self, broker=None):
        self.storage = TradeStorage()
        self.broker = broker  # Optional — if None, skips live account data

    def write(self):
        """
        Generate the full context file and write it to disk.
        Called every 15 minutes by the main scheduler.
        """
        try:
            content = self._build_context()
            CONTEXT_FILE.write_text(content, encoding="utf-8")
            logger.debug(f"Context file updated: {CONTEXT_FILE}")
        except Exception as e:
            logger.error(f"Failed to write context file: {e}")

    def _build_context(self) -> str:
        """Build the full markdown context file."""
        now = datetime.now(timezone.utc)
        sections = []

        # Header
        sections.append(self._header(now))

        # Account & live positions
        sections.append(self._account_section())

        # Today's trading
        sections.append(self._today_section(now))

        # This week
        sections.append(self._week_section())

        # All-time stats
        sections.append(self._alltime_section())

        # Recent trades with reasoning
        sections.append(self._recent_trades_section())

        # Bot configuration
        sections.append(self._config_section())

        # Footer instructions for Claude
        sections.append(self._claude_instructions())

        return "\n\n".join(sections)

    def _header(self, now: datetime) -> str:
        return f"""# Joseph's Forex Bot — Live Context
> **Last updated:** {now.strftime("%A %d %B %Y at %H:%M UTC")}
> **Environment:** {config.OANDA_ENVIRONMENT.upper()} {"(Demo — no real money)" if config.OANDA_ENVIRONMENT == "practice" else "⚠️ LIVE ACCOUNT"}

This file is automatically generated every 15 minutes by the trading bot.
It contains live trading data, performance statistics, and bot configuration.
Use it to ask questions and get deep analysis about trading activity."""

    def _account_section(self) -> str:
        lines = ["## 💰 Account Status"]

        if self.broker:
            try:
                balance = self.broker.get_account_balance()
                open_trades = self.broker.get_open_trades()
                deployed = self.broker.get_open_positions_value()

                lines.append(f"- **Balance:** £{balance:.2f}")
                lines.append(f"- **Capital Limit:** £{config.MAX_CAPITAL}")
                lines.append(f"- **Currently Deployed:** £{deployed:.2f}")
                lines.append(f"- **Available to Deploy:** £{max(0, config.MAX_CAPITAL - deployed):.2f}")
                lines.append(f"- **Open Positions:** {len(open_trades)}")

                if open_trades:
                    lines.append("\n### Open Positions Right Now")
                    for t in open_trades:
                        direction = "BUY" if int(t.get("currentUnits", 0)) > 0 else "SELL"
                        pl = float(t.get("unrealizedPL", 0))
                        pl_str = f"+£{pl:.2f}" if pl >= 0 else f"-£{abs(pl):.2f}"
                        pair = t.get("instrument", "").replace("_", "/")
                        lines.append(f"- **{pair}** | {direction} | Unrealised P&L: {pl_str}")
                else:
                    lines.append("- No open positions currently")

            except Exception as e:
                lines.append(f"- ⚠️ Could not fetch live account data: {e}")
        else:
            lines.append("- Live account data not available in this context")

        return "\n".join(lines)

    def _today_section(self, now: datetime) -> str:
        today = now.strftime("%Y-%m-%d")
        trades = self.storage.get_trades_for_date(today)

        lines = [f"## 📊 Today's Trading ({now.strftime('%A %d %B')})"]

        if not trades:
            lines.append("- No trades placed today yet")
            return "\n".join(lines)

        wins = [t for t in trades if t.get("pl", 0) > 0]
        losses = [t for t in trades if t.get("pl", 0) <= 0 and "pl" in t]
        open_today = [t for t in trades if "pl" not in t]
        net_pl = sum(t.get("pl", 0) for t in trades)
        win_rate = round(len(wins) / len(trades) * 100, 1) if trades else 0

        lines.append(f"- **Total Trades:** {len(trades)}")
        lines.append(f"- **Wins:** {len(wins)} | **Losses:** {len(losses)} | **Open:** {len(open_today)}")
        lines.append(f"- **Win Rate:** {win_rate}%")
        lines.append(f"- **Net P&L:** {'+'if net_pl >= 0 else ''}£{net_pl:.2f}")

        # P&L by pair today
        pair_pl = {}
        for t in trades:
            p = t.get("pair", "Unknown")
            pair_pl[p] = round(pair_pl.get(p, 0) + t.get("pl", 0), 2)

        if pair_pl:
            lines.append("\n**P&L by Pair Today:**")
            for pair, pl in sorted(pair_pl.items(), key=lambda x: x[1], reverse=True):
                sign = "+" if pl >= 0 else ""
                lines.append(f"- {pair.replace('_', '/')}: {sign}£{pl:.2f}")

        # Today's individual trades
        lines.append("\n**Individual Trades Today:**")
        for t in trades[-10:]:  # Last 10
            pair = t.get("pair", "?").replace("_", "/")
            direction = t.get("direction", "?")
            pl = t.get("pl", None)
            score = t.get("confidence_score", "?")
            reasoning = t.get("reasoning", "No reasoning recorded")
            time_str = t.get("opened_at", "")[:16].replace("T", " ")

            pl_str = f"P&L: {'+'if pl and pl >= 0 else ''}£{pl:.2f}" if pl is not None else "Still open"
            lines.append(
                f"- [{time_str}] **{pair}** {direction} | Score: {score}% | {pl_str}"
            )
            # Include reasoning so Claude can explain individual trades
            if reasoning:
                short_reasoning = reasoning.replace("\n", " ")[:200]
                lines.append(f"  - *Reason: {short_reasoning}*")

        return "\n".join(lines)

    def _week_section(self) -> str:
        trades = self.storage.get_trades_for_week()
        lines = ["## 📅 This Week's Performance"]

        if not trades:
            lines.append("- No trades this week yet")
            return "\n".join(lines)

        wins = [t for t in trades if t.get("pl", 0) > 0]
        net_pl = sum(t.get("pl", 0) for t in trades)
        win_rate = round(len(wins) / len(trades) * 100, 1) if trades else 0
        gross_profit = sum(t["pl"] for t in wins)
        gross_loss = abs(sum(t.get("pl", 0) for t in trades if t.get("pl", 0) < 0))
        profit_factor = round(gross_profit / gross_loss, 2) if gross_loss > 0 else 999

        lines.append(f"- **Total Trades:** {len(trades)}")
        lines.append(f"- **Win Rate:** {win_rate}%")
        lines.append(f"- **Net P&L:** {'+'if net_pl >= 0 else ''}£{net_pl:.2f}")
        lines.append(f"- **Gross Profit:** +£{gross_profit:.2f}")
        lines.append(f"- **Gross Loss:** -£{gross_loss:.2f}")
        lines.append(f"- **Profit Factor:** {profit_factor} (above 1.3 is healthy)")

        # P&L by pair this week
        pair_pl = {}
        pair_trades = {}
        pair_wins = {}
        for t in trades:
            p = t.get("pair", "Unknown")
            pair_pl[p] = round(pair_pl.get(p, 0) + t.get("pl", 0), 2)
            pair_trades[p] = pair_trades.get(p, 0) + 1
            if t.get("pl", 0) > 0:
                pair_wins[p] = pair_wins.get(p, 0) + 1

        lines.append("\n**Performance by Pair This Week:**")
        for pair in sorted(pair_pl, key=pair_pl.get, reverse=True):
            pl = pair_pl[pair]
            n = pair_trades[pair]
            wr = round(pair_wins.get(pair, 0) / n * 100) if n > 0 else 0
            sign = "+" if pl >= 0 else ""
            lines.append(f"- {pair.replace('_', '/')}: {sign}£{pl:.2f} ({n} trades, {wr}% win rate)")

        return "\n".join(lines)

    def _alltime_section(self) -> str:
        stats = self.storage.get_summary_stats()
        lines = ["## 🏆 All-Time Performance Statistics"]

        if "message" in stats:
            lines.append(f"- {stats['message']}")
            return "\n".join(lines)

        lines.append(f"- **Total Trades:** {stats.get('total_trades', 0)}")
        lines.append(f"- **Win Rate:** {stats.get('win_rate', 0)}%")
        lines.append(f"- **Net P&L:** {'+'if stats.get('total_pl',0) >= 0 else ''}£{stats.get('total_pl', 0):.2f}")
        lines.append(f"- **Profit Factor:** {stats.get('profit_factor', 0)} (target: >1.3)")
        lines.append(f"- **Average Win:** +£{stats.get('avg_win', 0):.2f}")
        lines.append(f"- **Average Loss:** -£{stats.get('avg_loss', 0):.2f}")
        lines.append(f"- **Gross Profit:** +£{stats.get('gross_profit', 0):.2f}")
        lines.append(f"- **Gross Loss:** -£{stats.get('gross_loss', 0):.2f}")

        return "\n".join(lines)

    def _recent_trades_section(self) -> str:
        all_trades = self.storage.get_all_trades()
        recent = all_trades[-10:] if all_trades else []
        lines = ["## 🔍 Last 10 Trades (with AI Reasoning)"]

        if not recent:
            lines.append("- No trade history yet")
            return "\n".join(lines)

        for t in reversed(recent):  # Most recent first
            pair = t.get("pair", "?").replace("_", "/")
            direction = t.get("direction", "?")
            pl = t.get("pl", None)
            score = t.get("confidence_score", "?")
            reasoning = t.get("reasoning", "No reasoning recorded")
            opened = t.get("opened_at", "")[:16].replace("T", " ") + " UTC"
            entry = t.get("fill_price", t.get("open_price", "?"))
            sl = t.get("stop_loss", "?")
            tp = t.get("take_profit", "?")

            pl_str = f"P&L: {'+'if pl and pl >= 0 else ''}£{pl:.2f}" if pl is not None else "Position still open"

            lines.append(f"\n**{pair} {direction}** | {opened}")
            lines.append(f"- Entry: {entry} | SL: {sl} | TP: {tp}")
            lines.append(f"- Confidence: {score}% | {pl_str}")
            lines.append(f"- *Reasoning: {reasoning[:300]}*")

        return "\n".join(lines)

    def _config_section(self) -> str:
        lines = [
            "## ⚙️ Current Bot Configuration",
            f"- **Environment:** {config.OANDA_ENVIRONMENT.upper()}",
            f"- **Max Capital at Risk:** £{config.MAX_CAPITAL}",
            f"- **Min Confidence to Trade:** {config.MIN_CONFIDENCE_SCORE}%",
            f"- **Overnight Hold Threshold:** {config.HOLD_OVERNIGHT_THRESHOLD}%",
            f"- **Pairs Trading:** {', '.join([p.replace('_', '/') for p in config.PAIRS])}",
            f"- **Max Open Positions:** {config.MAX_OPEN_POSITIONS}",
            f"- **Risk Per Trade:** {config.PER_TRADE_RISK_PCT}%",
            f"- **Scan Interval:** Every {config.SCAN_INTERVAL_MINUTES} minutes",
            f"- **Timeframe:** {config.TIMEFRAME} candles",
        ]
        return "\n".join(lines)

    def _claude_instructions(self) -> str:
        return """## 📌 Instructions for Claude (Claude Projects Integration)

You are Joseph's personal trading assistant with full access to his bot's live data above.

When Joseph asks questions:
- **"How am I doing?"** → Summarise today/week performance, highlight wins and losses
- **"Why did the bot make [trade]?"** → Find the trade in history and explain the reasoning
- **"What's my best/worst pair?"** → Analyse the P&L by pair data
- **"Should I change any settings?"** → Compare performance against benchmarks and suggest config changes
- **"Plan for tomorrow"** → Look at weekly performance trends and suggest a strategic approach
- **"What's my win rate?"** → Pull from all-time stats and break down by pair/session if possible

Be honest about weaknesses. If a pair is consistently losing, say so clearly.
If the win rate is below 50%, flag it. If profit factor is below 1.3, explain why that matters.

Always ground your answers in the actual data above. Never make up numbers."""
